#!/usr/bin/env python3
"""Emit ui/strings/CONTEXT.md -- where each translatable string actually appears.

A translator handed a bare list of strings cannot tell a verb from a noun. In THIS UI
"Home" is a button that drives a reel to its zero position (a verb), "Flap" is a physical
character leaf, "Display" is both a tab and the wall itself, and "Save"/"Revert" are
buttons while "Serial Number"/"Last Seen" are table headings. Same word, different part
of speech, different translation.

So for every key we record the screen it is on and the kind of control it is, and hand
THAT to the translator and the reviewer. It is the difference between a translation that
parses and one that is right.

Run: python3 tools/i18n_context.py
"""
import html
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
UI = ROOT / "ui" / "index.html"
OUT = ROOT / "ui" / "strings" / "CONTEXT.md"

PANE = {
    "modules": "Modules tab (the module grid)",
    "display": "Display tab (send text/characters to the wall)",
    "provision": "Provision tab (assign bus IDs)",
    "calib": "Calibration tab (tune a module's flap positions)",
    "monitor": "Bus Monitor tab (live RS-485 traffic)",
    "settings": "Settings tab",
    "statusp": "Status tab (diagnostics)",
}
KIND = {
    "button": "BUTTON (an action -- use the imperative)",
    "h2": "HEADING (card title -- a noun phrase)",
    "h3": "HEADING",
    "label": "FORM LABEL (names the input below it -- a noun phrase)",
    "option": "DROPDOWN OPTION",
    "p": "HELP TEXT (a full sentence)",
    "span": "INLINE TEXT",
    "div": "TEXT",
    "a": "TAB / LINK LABEL (a noun)",
    "small": "SMALL PRINT",
    "b": "EMPHASIS",
}


def main():
    page = UI.read_text(encoding="utf-8")
    en = json.loads((ROOT / "ui" / "strings" / "en.json").read_text(encoding="utf-8"))
    keys = [k for k in en if k != "$name"]

    # Where does each pane start/end, so a match offset maps to a screen?
    bounds = []
    for m in re.finditer(r'id="pane-(\w+)"', page):
        bounds.append((m.start(), m.group(1)))
    bounds.sort()

    def pane_at(pos):
        cur = None
        for start, name in bounds:
            if start <= pos:
                cur = name
            else:
                break
        return PANE.get(cur, "—")

    ctx = {k: set() for k in keys}
    # <tag ...>TEXT</tag>  -- gives us the element kind AND the position (hence the pane)
    for m in re.finditer(r'<(\w+)[^>]*>([^<>]{1,240}?)</\1>', page):
        tag, txt = m.group(1), html.unescape(m.group(2)).strip()
        txt = re.sub(r'^[^0-9A-Za-z]+', '', txt).strip()
        if txt in ctx:
            ctx[txt].add((pane_at(m.start()), KIND.get(tag, tag.upper())))
    # attributes
    for m in re.finditer(r'(placeholder|title)="([^"]+)"', page):
        av = html.unescape(m.group(2)).strip()
        if av in ctx:
            kind = "INPUT PLACEHOLDER (example text)" if m.group(1) == "placeholder" else "TOOLTIP"
            ctx[av].add((pane_at(m.start()), kind))
    # t("...") -- a runtime message; note the function it lives in
    for m in re.finditer(r't\((["\'])(.*?)\1\)', page):
        lit = m.group(2).strip()
        if lit in ctx:
            fn = None
            head = page.rfind("function ", 0, m.start())
            if head != -1:
                fn = re.match(r'function\s+(\w+)', page[head:head + 60])
            ctx[lit].add(("—", f"RUNTIME MESSAGE (shown after an action{', in ' + fn.group(1) + '()' if fn else ''})"))

    lines = [
        "# Where each string appears",
        "",
        "Generated by `tools/i18n_context.py` -- do not edit.",
        "",
        "Use this when translating: the same English word is often a different part of",
        "speech in different places. In this UI **Home** is a verb (drive a reel to its zero",
        "position), **Flap** is the physical character leaf on the reel, **Display** is both a",
        "tab and the wall itself, and **Save**/**Revert** are buttons while **Serial Number**",
        "and **Last Seen** are table headings.",
        "",
        "| English | Where | What kind of thing it is |",
        "|---|---|---|",
    ]
    for k in keys:
        c = sorted(ctx[k])
        where = "; ".join(sorted({w for w, _ in c if w != "—"})) or "—"
        kind = "; ".join(sorted({d for _, d in c})) or "(built at runtime)"
        esc = k.replace("|", "\\|")
        lines.append(f"| `{esc}` | {where} | {kind} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    known = sum(1 for k in keys if ctx[k])
    print(f"{OUT.relative_to(ROOT)}: {len(keys)} keys, {known} with a located context")


if __name__ == "__main__":
    main()
